import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "./StoreProvide"
import './globals.css';
import Navbar from "@/app/navBar";
import {AppAlertProvider} from "@/app/AppAlertContext";
import {Alert} from "@/app/Alert";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <Provider>
      <AppAlertProvider>
      <body className="flex flex-1 gap-3">
      <Alert />
          <Navbar />
          {children}
      </body>
        </AppAlertProvider>
    </Provider>
    </html>
  );
}
